export default [
  '/',
  // FIXME Can't render Getty 404 page on https://static-www.aws.getty.edu/
  // '/404/',
  '/about/',
  '/about/contact/',
  '/about/facts/',
  '/about/history/',
  '/about/join-and-give/',
  '/about/join-and-give/contact/',
  '/about/join-and-give/faqs/',
  '/about/join-and-give/getty-fund/',
  '/about/join-and-give/corporate-partnerships/',
  '/about/join-and-give/patron-program/',
  '/about/join-and-give/planned-giving/',
  '/about/join-and-give/support/',
  '/about/join-and-give/volunteer/',
  '/about/leadership-governance/',
  '/about/leadership-governance/board/',
  '/about/leadership-governance/policies/',
  '/about/leadership-governance/financials/',
  // FIXME 404
  // '/accessibility/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/art/',
  '/author/butler-meg/',
  // FIXME Calendar pages take a very long time to load due to AV being slow, and causes chromatic to throw an error
  // '/calendar/',
  // '/calendar/this-weekend/',
  // '/calendar/today/',
  // '/calendar/tomorrow/',
  '/calendar/backstage-black-archives-and-memory/',
  '/calendar/focus-tour-brush-nature/',
  '/conservation/',
  '/databases-tools-and-technologies/provenance/',
  // FIXME this path was causing chromatic to throw an error
  // '/databases-tools-and-technologies/provenance/gpi-user-guide/',
  '/databases-tools-and-technologies/provenance/faqs/',
  '/databases-tools-and-technologies/provenance/whats-covered/',
  '/education/teachers/pst-art-art-science-collide/',
  // FIXME 404
  // '/education/teachers/pst-art-art-science-collide/meet-simon-denis/',
  '/education/teachers/pst-art-art-science-collide/cloudy-with-a-chance-of-classical-art/',
  '/exhibitions/',
  '/exhibitions/?tab=current',
  '/exhibitions/?tab=future',
  '/exhibitions/?location=getty-center',
  '/exhibitions/?location=getty-villa',
  '/exhibitions/?location=online',
  '/exhibitions/charles-ross-spectrum-14/',
  '/foundation/',
  '/foundation/staff/',
  '/funding/',
  '/funding/impact-reports/',
  '/funding/opportunities/',
  '/funding/residential-grants/',
  '/museum/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/museum/antiquities-conservation/',
  // '/museum/antiquities/',
  // '/museum/decorative-arts-and-sculpture-conservation/',
  // '/museum/drawings/',
  // '/museum/manuscripts/',
  // '/museum/paintings/',
  '/museum/paintings-conservation/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/museum/paper-conservation/',
  // '/museum/photographs/',
  // '/museum/sculpture-decorative-arts/',
  '/museum/paintings/staff/',
  '/museum/deaccessioning/',
  '/museum/image-request/',
  '/news/',
  // FIXME /news/all takes too long to load results and causes chromatic to throw an error
  // '/news/all/',
  // FIXME 404
  // '/news/tag/espagnol/',
  '/news/topic/art-architecture/',
  '/news/journalists/',
  '/news/magazine/',
  '/news/renaissance-left-handed-drawing-Leonardo-da-Vinci-forgery/',
  '/news/over-1-700-artists-and-arts-workers-in-la-receive-14-3-million-for-urgent-fire-relief/',
  '/our-work/',
  '/podcasts/',
  '/podcasts/recording-artists/',
  '/podcasts/recording-artists/why-doesnt-he-dance-a-little-better/',
  '/projects/',
  '/projects/herculaneum-conservation-tablinum-house-of-bicentenary/',
  '/projects/herculaneum-conservation-tablinum-house-of-bicentenary/herculaneum-scientific-investigation/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/publications/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/publications-reports/',
  '/publications/getty-research-journal/',
  '/publications/getty-research-journal/journal-policies/',
  '/publications/for-authors/',
  '/publications/for-booksellers-media-educators/',
  '/research/',
  '/research-conservation/',
  '/research-conservation/library/',
  '/research-conservation/library/about/',
  '/research-conservation/library/reader-registration/',
  '/search/',
  '/visit/',
  '/visit/app/',
  '/visit/photo-and-video-policy/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/visit/center/',
  '/visit/center/accessibility/',
  '/visit/center/food-and-drink/',
  '/visit/center/parking-and-transportation/',
  '/visit/center/shopping/',
  '/visit/center/family-visits/',
  '/visit/center/group-visits/',
  '/visit/center/faqs/',
  '/visit/center/top-things-to-do/',
  '/visit/center/top-things-to-do/art/',
  '/visit/center/top-things-to-do/architecture/',
  '/visit/center/top-things-to-do/gardens/',
  // FIXME chromatic errors https://www.chromatic.com/build?appId=65988130e380e4c782b3ca13&number=19
  // '/visit/villa/',
  '/visit/villa/accessibility/',
  '/visit/villa/food-and-drink/',
  '/visit/villa/parking-and-transportation/',
  '/visit/villa/shopping/',
  '/visit/villa/family-visits/',
  '/visit/villa/group-visits/',
  '/visit/villa/faqs/',
  '/visit/villa/top-things-to-do/',
  '/visit/villa/top-things-to-do/art/',
  '/visit/villa/top-things-to-do/architecture/',
  '/visit/villa/top-things-to-do/gardens/',
  '/whats-on/',
  '/whats-on/pst-art-art-science-collide/'
];
